apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sre-challenge
  name: sre-challenge
  namespace: sre-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-challenge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sre-challenge
    spec:
      containers:
      - image: sre-challenge
        name: sre-challenge
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        resources: {}
status: {}
